# repo_02_admin_core/main.py
import os
import asyncio
import logging
import time
from typing import Optional
from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes
from supabase import create_client, Client
from dotenv import load_dotenv

# --- Настройка ---
load_dotenv()
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

TELEGRAM_BOT_TOKEN_ADMIN = os.getenv("TELEGRAM_BOT_TOKEN_ADMIN")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY_FOR_ADMIN") 

supabase: Optional[Client] = create_client(SUPABASE_URL, SUPABASE_KEY)

# --- Логика ИИ и Генерации Стратегии (НОВАЯ ФУНКЦИЯ) ---

async def generate_new_strategy():
    """
    ТЯЖЕЛЫЙ ПРОЦЕСС: Анализ статистики Supabase и генерация нового алгоритма.
    Эта функция запускается по расписанию или команде.
    """
    logger.info("🧠 Running AI analysis and strategy generation...")
    if not supabase: return

    try:
        # 1. Чтение прошлых трейдов и сигналов из Supabase
        # response = supabase.table("trades").select("*").limit(100).execute()
        # past_data = pd.DataFrame(response.data)
        
        # 2. ИИ-анализ (логика ML или LLM) - здесь будет самая большая нагрузка
        # new_algorithm_rules = run_heavy_ai_model(past_data)

        # 3. Генерация новой стратегии
        new_strategy = {
            "name": f"Strategy_{int(time.time())}",
            "is_active": True,
            "assets_to_monitor": ["EURUSD=X", "GBPJPY=X"],
            "default_amount": 15.0,
            "default_timeframe": 120,
            "algorithm_rules": "RSI < 30 AND MACD Cross UP", # Чистый, легкий алгоритм для Ядра
            "description": "Generated by AI based on last week's best performing assets."
        }

        # 4. Запись в Supabase (отключаем старые, включаем новую)
        supabase.table("strategy_settings").update({"is_active": False}).execute()
        supabase.table("strategy_settings").insert(new_strategy).execute()
        
        logger.info(f"✅ New strategy '{new_strategy['name']}' deployed to Supabase.")

    except Exception as e:
        logger.error(f"❌ Error in AI strategy generation: {e}")

# --- Telegram Bot Логика ---

async def manage_strategy_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Обрабатывает команду /ai_run (запуск генерации алгоритма)."""
    await update.message.reply_text("⏳ Запускаю тяжелый процесс AI-анализа и генерации новой стратегии. Это может занять несколько минут...")
    
    # Запускаем тяжелый процесс в отдельном потоке, чтобы не блокировать Telegram
    await asyncio.to_thread(asyncio.run, generate_new_strategy()) 
    
    await update.message.reply_text("✅ Генерация стратегии завершена! Ядро Render начнет использовать новый алгоритм в следующем цикле.")


# Здесь будут остальные админ-команды: /view_logs, /view_users, /block_user

def run_admin_bot():
    """Запускает Telegram-бот."""
    if not TELEGRAM_BOT_TOKEN_ADMIN:
        logger.error("🚫 TELEGRAM_BOT_TOKEN_ADMIN не задан.")
        return

    application = Application.builder().token(TELEGRAM_BOT_TOKEN_ADMIN).build()
    application.add_handler(CommandHandler("ai_run", manage_strategy_command))
    
    application.run_polling(poll_interval=1.0)


if __name__ == "__main__":
    run_admin_bot()

